### ISSUE TITLE
Requisitos U1

### ISSUE THREAD

**Issue by filipemalgueiro** [davileahy/Bigu#1]
PROVA DIA 24/04/204
- [x] protótipo funcional
- [x]  framework definido
- [x] linguagem definida
- [x] algoritmo definido
- [x] funcionamento local
- [x] entrada definida para o teste (lista de objetos)
- [x] gerenciamento de projeto através do método ágil escolhido, através de um software (trello)
- [x] controle de versão do software atual (GIT)
- [x] artigo ou artigos que justificam o trabalho e o algoritmo utilizado. (2 ou mais artigos)

**Comment by 21vito** [comment]
boraa
